<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
	    <TargetFramework>net10.0-windows</TargetFramework>
		<AssemblyTitle>AutoUpdater.NET</AssemblyTitle>
        <Description>AutoUpdater.NET is a class library that allows .NET developers to easily add auto update functionality to their WinForms or WPF application projects.</Description>
        <Nullable>enable</Nullable>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <PackageProjectUrl>https://github.com/Latency/AutoUpdater.NET</PackageProjectUrl>
        <PackageReleaseNotes>https://github.com/Latency/AutoUpdater.NET/releases</PackageReleaseNotes>
        <PackageTags>autoupdate updater c# wpf</PackageTags>
        <Product>AutoUpdater.NET</Product>
        <RootNamespace>AutoUpdaterDotNET</RootNamespace>
        <Title>AutoUpdater.NET</Title>
        <UseWpf>true</UseWpf>
        <Version>2.0.0</Version>
        <OutputType>WinExe</OutputType>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <ItemGroup>
      <Compile Remove="Views\DownloadUpdateDialog.cs" />
      <Compile Remove="Views\DownloadUpdateDialog.Designer.cs" />
    </ItemGroup>

    <ItemGroup>
      <Content Remove="bin\Debug\net10.0-windows\README.md" />
    </ItemGroup>

	<ItemGroup>
      <ApplicationDefinition Include="Views\App.xaml" />
    </ItemGroup>

    <ItemGroup>
	    <PackageReference Include="Extended.Wpf.Toolkit" Version="4.7.25104.5739" />
	    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.14.0" />
	    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.0-preview.5.25277.114" />
	    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.0-preview.5.25277.114" />
    </ItemGroup>

    <ItemGroup>
      <Resource Include="png\clock_go.png" />
      <Resource Include="png\clock_play.png" />
      <Resource Include="png\download.png" />
      <Resource Include="png\hand_point.png" />
      <Resource Include="png\update.png" />
    </ItemGroup>

	<Import Project="D:\Source\Directory.PostBuild.props" Condition="Exists('D:\Source\Directory.PostBuild.props')" />

</Project>