<Project>

	<Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Build.targets', '$(MSBuildThisFileDirectory)../../'))"
		Condition="Exists($([MSBuild]::GetPathOfFileAbove('Directory.Build.targets', '$(MSBuildThisFileDirectory)../../')))" />

	<!-- Create a Target to execute tasks -->
	<Target Name="LaunchSettings" AfterTargets="PrepareForBuild">
		<Message Text="Building in $(Configuration) mode..." Importance="high" />	
		<Message Text="Modifing '$(PropertySourceFile)'..." Importance="high" />
		<InsertIntoFile FilePath="$(PropertySourceFile)" LineNumber="12" Text="$(IconText)" />
	</Target>

	<UsingTask
		TaskName="InsertIntoFile"
		TaskFactory="CodeTaskFactory"
		AssemblyFile="$(MSBuildToolsPath)\Microsoft.Build.Tasks.Core.dll" >
		<ParameterGroup>
			<FilePath ParameterType="System.String" Required="true" />
			<LineNumber ParameterType="System.Int32"  Required="true" />
			<Text ParameterType="System.String" Required="false" />
		</ParameterGroup>
		<Task>
			<Using Namespace="System" />
			<Using Namespace="System.IO" />
			<Code Type="Fragment" Language="cs">
				<![CDATA[
                // By tradition, text file line numbering is 1-based
                var lines = File.Exists(FilePath)
                                      ? File.ReadAllLines(FilePath).ToList() 
                                      : new List<String>(1);
				var index = Math.Min(LineNumber - 1, lines.Count);
				var line = lines[index];
				
				if (Text == null)
				{
					if (line.Contains("IconFile"))
					{
						lines.RemoveAt(index);
						File.WriteAllLines(FilePath, lines);	
					}
				}
				else
				{
					if (line != Text)
					{
					    lines.Insert(index, Text);
		                File.WriteAllLines(FilePath, lines);
					}
				}
                return true;
              ]]>
			</Code>
		</Task>
	</UsingTask>

</Project>